[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  anvil = "http://localhost:8545"
  btp = "${BTP_RPC_URL}"

[profile.default]
  src = 'contracts'
  out = 'out'
  libs = ['node_modules', 'lib']
  test = 'test'
  cache_path  = 'cache_forge'
  solc = "0.8.28"
  optimizer = true
  optimizer_runs = 200
  gas_reports = ["*"]
  fuzz = { runs = 1_000 }
  auto_detect_solc = false
  extra_output_files = [ "metadata" ]
  viaIR = true

# Soldeer configuration
[soldeer]
  remappings_version = false

[dependencies]
  forge-std = "1.9.6"
  "@openzeppelin-contracts" = "5.2.0"
  "@openzeppelin-contracts-upgradeable" = "5.2.0"
  "@onchainid" = { version = "v2.2.1", git = "https://github.com/onchain-id/solidity.git", rev = "2.2.1" }
