[dependencies]
  # Core dependencies
  forge-std = "1.9.5"
  "@openzeppelin-contracts" = "5.2.0"
  # "@openzeppelin-community-contracts" = { version = "0.0.1", git = "https://github.com/OpenZeppelin/openzeppelin-community-contracts" }